// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Ml_dex_industrial_intership
{
    public partial class MLAnimeRatingPredictor
    {
        /// <summary>
        /// model input class for MLAnimeRatingPredictor.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"name")]
            public string Name { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"genre")]
            public string Genre { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"type")]
            public string Type { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"episodes")]
            public float Episodes { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"rating")]
            public float Rating { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"members")]
            public float Members { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLAnimeRatingPredictor.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"name")]
            public float[] Name { get; set; }

            [ColumnName(@"genre")]
            public float[] Genre { get; set; }

            [ColumnName(@"type")]
            public float[] Type { get; set; }

            [ColumnName(@"episodes")]
            public float Episodes { get; set; }

            [ColumnName(@"rating")]
            public float Rating { get; set; }

            [ColumnName(@"members")]
            public float Members { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLAnimeRatingPredictor.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
